# Generated by Django 4.0 on 2022-01-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_marketname_market_marketname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'managed': False},
        ),
    ]
